services:
  db:
    container_name: postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'ny_taxi'
    ports:
      - '5433:5432'
    volumes:
      - vol-pgdata:/var/lib/postgresql/data
    networks:
      - db-network

  pgadmin:
    container_name: pgadmin
    image: pgadmin_homework_1
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@pgadmin.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    ports:
      - "8080:80"
    volumes:
      - vol-pgadmin_data:/var/lib/pgadmin  
    networks:
      - db-network
      
  taxi_data_ingestion:
    container_name: taxi_data_ingestion
    image: taxi_file_ingestion:latest
    networks:
      - db-network
    pull_policy: never
    volumes:
      - ./taxi_data:/taxi_data
    depends_on:
      - db

volumes:
  vol-pgdata:
    name: vol-pgdata
  vol-pgadmin_data:
    name: vol-pgadmin_data
  vol-taxi_data:
    name: vol-taxi_data

networks:
  db-network:
    driver: bridge
